### ISSUE TITLE
feat: error handling

### ISSUE THREAD

**Issue by dai-shi** [jotai-labs/jotai-apollo#2]
In jotai, we implement "error handling" recently.

- https://github.com/pmndrs/jotai/pull/1239 for jotai/query
- https://github.com/pmndrs/jotai/pull/1381 for jotai/urql
- https://github.com/jotai-labs/jotai-relay for jotai-relay

jotai-apollo should follow it so that we can recommend it.
I think you want to refer `jotai/urql` implementation, which is almost the same as `jotai-relay`.
(`jotai/query` is very unique/weird implementation, hope to fix it too eventually.)

**Comment by Aslemammad** [comment]
Check this https://github.com/jotai-labs/jotai-apollo/commit/3902497335abf7c1def69d22bd123d3f078e2304 and let me know your opinion.

**Comment by dai-shi** [comment]
Thanks for working on it. I would avoid relaying on `Math.random` in tests.

btw, I made a new implementation in https://github.com/jotai-labs/jotai-urql.
It will supersede jotai/urql. https://github.com/pmndrs/jotai/pull/1473

We want to follow that new implementation. I will also apply it to jotai-relay.

**Comment by Aslemammad** [comment]
Sure, ok!

**Comment by Aslemammad** [comment]
Hey @dai-shi, Feel free to review the new impl of atomsWithQuery. And let me know if you think it's proper and I can follow it in other atoms.

**Comment by dai-shi** [comment]
@Aslemammad Can you make it a draft PR?
